"use client";

/* eslint-disable @next/next/no-img-element, @next/next/no-html-link-for-pages */
import { useCallback, useEffect, useMemo, useState } from "react";
import { createClient, type SupabaseClient } from "@supabase/supabase-js";
import { ArrowLeft, GripVertical, ImagePlus, LogOut, Plus, Save, Search, Trash2, Upload, X } from "lucide-react";

type Config = { url: string; publishableKey: string };
type VenueRow = { id: string; slug: string; name: string; venue_type: string | null; district: string | null; neighborhood: string | null; area_label: string | null; address_display: string; nearest_station: string | null; phone: string | null; official_url: string | null; capacity_people: number | null; stage_size: string | null; last_checked_at: string | null; verification_status: string; location_verified: boolean; latitude: number | null; longitude: number | null };
type DetailState = { weekday_text: string; weekday_price: string; weekend_text: string; weekend_price: string; source_url: string; sound_engineer: string; lighting_operator: string; foh_console: string; main_pa: string; monitor_system: string; wired_mics: string; wireless_mics: string; di_boxes: string; parking: string; waiting_room: string; elevator: string; easy_load_in: string };
type EquipmentRow = { category: string; raw_description: string };
type ImageRow = { id: string; public_url: string; storage_path: string; sort_order: number };
const blankDetails: DetailState = { weekday_text: "", weekday_price: "", weekend_text: "", weekend_price: "", source_url: "", sound_engineer: "", lighting_operator: "", foh_console: "", main_pa: "", monitor_system: "", wired_mics: "", wireless_mics: "", di_boxes: "", parking: "", waiting_room: "", elevator: "", easy_load_in: "" };
const equipmentCategoryLabels: Record<string, string> = { drums: "드럼", guitar_amp: "기타앰프", bass_amp: "베이스앰프", keyboard: "건반", lighting_fixture: "조명기", lighting_console: "조명 콘솔", moving_light: "무빙 라이트", follow_spot: "팔로우 스폿", other: "기타" };

function nullableBool(value: string) { return value === "true" ? true : value === "false" ? false : null; }

export function AdminConsole({ config }: { config: Config }) {
  const supabase = useMemo<SupabaseClient | null>(() => config.url && config.publishableKey ? createClient(config.url, config.publishableKey) : null, [config]);
  const [auth, setAuth] = useState<"loading" | "signed_out" | "checking" | "admin" | "denied">("loading");
  const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [message, setMessage] = useState("");
  const [venues, setVenues] = useState<VenueRow[]>([]); const [selectedId, setSelectedId] = useState<string>(""); const [form, setForm] = useState<Partial<VenueRow>>({});
  const [details, setDetails] = useState<DetailState>(blankDetails); const [equipment, setEquipment] = useState<EquipmentRow[]>([]); const [images, setImages] = useState<ImageRow[]>([]);
  const [newEquipment, setNewEquipment] = useState<EquipmentRow>({ category: "drums", raw_description: "" }); const [saving, setSaving] = useState(false);
  const [uploadingImages, setUploadingImages] = useState(false); const [uploadProgress, setUploadProgress] = useState({ current: 0, total: 0 });
  const [draggedImageId, setDraggedImageId] = useState<string | null>(null); const [savingImageOrder, setSavingImageOrder] = useState(false);
  const [venueSearch, setVenueSearch] = useState("");
  const visibleVenues = venues.filter((venue) => [venue.name, venue.area_label, venue.address_display].filter(Boolean).join(" ").toLowerCase().includes(venueSearch.trim().toLowerCase()));

  const loadVenues = useCallback(async () => { if (!supabase) return; const { data, error } = await supabase.from("venues").select("*").order("name"); if (error) setMessage(error.message); else { setVenues((data ?? []) as VenueRow[]); if (data?.[0]) setSelectedId((current) => current || data[0].id); } }, [supabase]);
  const checkAdmin = useCallback(async () => { if (!supabase) return; const { data: sessionData } = await supabase.auth.getSession(); const user = sessionData.session?.user; if (!user) { setAuth("signed_out"); return; } setAuth("checking"); const { data } = await supabase.from("admin_users").select("user_id").eq("user_id", user.id).maybeSingle(); setAuth(data ? "admin" : "denied"); if (data) await loadVenues(); }, [supabase, loadVenues]);

  useEffect(() => { if (!supabase) return; queueMicrotask(() => void checkAdmin()); const { data } = supabase.auth.onAuthStateChange(() => void checkAdmin()); return () => data.subscription.unsubscribe(); }, [supabase, checkAdmin]);

  useEffect(() => { const row = venues.find((venue) => venue.id === selectedId); if (!row || !supabase) return; void (async () => {
    setForm(row);
    const [staff, audio, facilities, rates, gear, photos, sources] = await Promise.all([
      supabase.from("venue_staff").select("*").eq("venue_id", row.id).maybeSingle(), supabase.from("audio_systems").select("*").eq("venue_id", row.id).maybeSingle(),
      supabase.from("venue_facilities").select("*").eq("venue_id", row.id).maybeSingle(), supabase.from("rental_rates").select("*").eq("venue_id", row.id),
      supabase.from("venue_equipment").select("category,raw_description").eq("venue_id", row.id), supabase.from("venue_images").select("*").eq("venue_id", row.id).order("sort_order").order("created_at"), supabase.from("sources").select("url,kind").eq("venue_id", row.id),
    ]);
    const weekday = rates.data?.find((rate) => rate.day_type === "weekday" || rate.day_type === "hourly"); const weekend = rates.data?.find((rate) => rate.day_type === "saturday" || rate.day_type === "sunday");
    setDetails({ weekday_text: weekday?.raw_text ?? "", weekday_price: weekday?.price_krw?.toString() ?? "", weekend_text: weekend?.raw_text ?? "", weekend_price: weekend?.price_krw?.toString() ?? "", source_url: sources.data?.find((source) => source.kind === "mule")?.url ?? "", sound_engineer: String(staff.data?.sound_engineer_included ?? ""), lighting_operator: String(staff.data?.lighting_operator_included ?? ""), foh_console: audio.data?.foh_console ?? "", main_pa: audio.data?.main_pa ?? "", monitor_system: audio.data?.monitor_system ?? "", wired_mics: audio.data?.wired_mics ?? "", wireless_mics: audio.data?.wireless_mics ?? "", di_boxes: audio.data?.di_boxes ?? "", parking: String(facilities.data?.parking ?? ""), waiting_room: String(facilities.data?.waiting_room ?? ""), elevator: String(facilities.data?.elevator ?? ""), easy_load_in: String(facilities.data?.easy_load_in ?? "") });
    setEquipment((gear.data ?? []) as EquipmentRow[]); setImages((photos.data ?? []) as ImageRow[]);
  })(); }, [selectedId, venues, supabase]);

  if (!config.url || !config.publishableKey) return <AdminFrame><div className="admin-setup"><h1>관리자 연결을 준비 중입니다</h1><p>Supabase 프로젝트 URL과 Publishable Key 설정이 완료되면 로그인할 수 있습니다.</p><a href="/">목록으로 돌아가기</a></div></AdminFrame>;
  if (auth === "loading" || auth === "checking") return <AdminFrame><div className="admin-setup"><p>관리자 권한을 확인하고 있습니다.</p></div></AdminFrame>;
  if (auth === "signed_out") return <AdminFrame><form className="admin-login" onSubmit={async (event) => { event.preventDefault(); setMessage(""); const { error } = await supabase?.auth.signInWithPassword({ email, password }) ?? { error: new Error("연결 오류") }; if (error) setMessage(error.message); }}><p>MATRIX ADMIN</p><h1>관리자 로그인</h1><label>이메일<input type="email" value={email} onChange={(event) => setEmail(event.target.value)} required /></label><label>비밀번호<input type="password" value={password} onChange={(event) => setPassword(event.target.value)} required /></label>{message && <span>{message}</span>}<button type="submit">로그인</button><a href="/">목록으로 돌아가기</a></form></AdminFrame>;
  if (auth === "denied") return <AdminFrame><div className="admin-setup"><h1>접근 권한이 없습니다</h1><p>현재 계정은 MATRIX 관리자로 등록되지 않았습니다.</p><button onClick={() => void supabase?.auth.signOut()}>로그아웃</button></div></AdminFrame>;

  const save = async () => { if (!supabase || !selectedId) return; setSaving(true); setMessage(""); const original = venues.find((venue) => venue.id === selectedId); const addressChanged = original?.address_display !== form.address_display; const base = { name: form.name, slug: form.slug, venue_type: form.venue_type || null, district: form.district || null, neighborhood: form.neighborhood || null, area_label: form.area_label || "기타", address_display: form.address_display, nearest_station: form.nearest_station || null, phone: form.phone || null, official_url: form.official_url || null, capacity_people: form.capacity_people ? Number(form.capacity_people) : null, stage_size: form.stage_size || null, last_checked_at: form.last_checked_at || null, verification_status: form.verification_status || "unverified", location_verified: addressChanged ? false : Boolean(form.location_verified), ...(addressChanged ? { latitude: null, longitude: null, geocoded_at: null, geocoded_address: null, address_hash: null } : {}) };
    const results = await Promise.all([
      supabase.from("venues").update(base).eq("id", selectedId),
      supabase.from("venue_staff").upsert({ venue_id: selectedId, sound_engineer_included: nullableBool(details.sound_engineer), lighting_operator_included: nullableBool(details.lighting_operator) }),
      supabase.from("audio_systems").upsert({ venue_id: selectedId, foh_console: details.foh_console || null, main_pa: details.main_pa || null, monitor_system: details.monitor_system || null, wired_mics: details.wired_mics || null, wireless_mics: details.wireless_mics || null, di_boxes: details.di_boxes || null }),
      supabase.from("venue_facilities").upsert({ venue_id: selectedId, parking: nullableBool(details.parking), waiting_room: nullableBool(details.waiting_room), elevator: nullableBool(details.elevator), easy_load_in: nullableBool(details.easy_load_in) }),
    ]);
    const error = results.find((result) => result.error)?.error; if (!error) { await supabase.from("rental_rates").delete().eq("venue_id", selectedId).in("day_type", ["weekday", "saturday"]); const rates = [{ venue_id: selectedId, day_type: "weekday", raw_text: details.weekday_text, price_krw: details.weekday_price ? Number(details.weekday_price) : null }, { venue_id: selectedId, day_type: "saturday", raw_text: details.weekend_text, price_krw: details.weekend_price ? Number(details.weekend_price) : null }].filter((rate) => rate.raw_text); if (rates.length) await supabase.from("rental_rates").insert(rates); await supabase.from("sources").delete().eq("venue_id", selectedId).eq("kind", "mule"); if (details.source_url) await supabase.from("sources").insert({ venue_id: selectedId, kind: "mule", url: details.source_url }); setMessage("저장했습니다. 사용자 화면에 즉시 반영됩니다."); await loadVenues(); } else setMessage(error.message); setSaving(false); };
  const addVenue = async () => { if (!supabase) return; const name = window.prompt("새 공연장 이름을 입력하세요.")?.trim(); if (!name) return; const address = window.prompt("확인된 공연장 주소를 입력하세요.")?.trim(); if (!address) return; const suffix = Date.now().toString(36); const { data, error } = await supabase.from("venues").insert({ name, slug: `venue-${suffix}`, address_display: address, area_label: "기타", verification_status: "unverified", location_verified: false }).select().single(); if (error) setMessage(error.message); else { await loadVenues(); setSelectedId(data.id); } };
  const deleteVenue = async () => { if (!supabase || !selectedId || !window.confirm("이 공연장과 연결된 정보를 삭제할까요?")) return; const { error } = await supabase.from("venues").delete().eq("id", selectedId); if (error) setMessage(error.message); else { setSelectedId(""); await loadVenues(); } };
  const uploadImages = async (files: FileList | null) => {
    if (!supabase || !selectedId || !files?.length || uploadingImages) return;
    const pendingFiles = Array.from(files); const firstSortOrder = images.reduce((max, image) => Math.max(max, image.sort_order), -1) + 1;
    setUploadingImages(true); setUploadProgress({ current: 0, total: pendingFiles.length }); setMessage(`이미지 업로드 중 (0/${pendingFiles.length})`);
    try {
      for (let index = 0; index < pendingFiles.length; index += 1) {
        const file = pendingFiles[index]; const safeName = `${selectedId}/${crypto.randomUUID()}-${file.name.replace(/[^a-zA-Z0-9._-]/g, "-")}`;
        setMessage(`이미지 업로드 중 (${index + 1}/${pendingFiles.length})`);
        const { error: storageError } = await supabase.storage.from("venue-images").upload(safeName, file, { upsert: false });
        if (storageError) { setMessage(`이미지 업로드 실패: ${storageError.message}`); return; }
        const publicUrl = supabase.storage.from("venue-images").getPublicUrl(safeName).data.publicUrl;
        const { data, error: rowError } = await supabase.from("venue_images").insert({ venue_id: selectedId, storage_path: safeName, public_url: publicUrl, sort_order: firstSortOrder + index }).select("id,public_url,storage_path,sort_order").single();
        if (rowError) { await supabase.storage.from("venue-images").remove([safeName]); setMessage(`이미지 정보 저장 실패: ${rowError.message}`); return; }
        setImages((current) => [...current, data as ImageRow]); setUploadProgress({ current: index + 1, total: pendingFiles.length });
      }
      setMessage(`${pendingFiles.length}개 이미지 업로드가 완료되었습니다.`);
    } finally { setUploadingImages(false); }
  };
  const moveImage = async (targetId: string) => {
    if (!supabase || !draggedImageId || draggedImageId === targetId || savingImageOrder) { setDraggedImageId(null); return; }
    const previous = images; const fromIndex = previous.findIndex((image) => image.id === draggedImageId); const toIndex = previous.findIndex((image) => image.id === targetId);
    if (fromIndex < 0 || toIndex < 0) { setDraggedImageId(null); return; }
    const reordered = [...previous]; const [moved] = reordered.splice(fromIndex, 1); reordered.splice(toIndex, 0, moved); const normalized = reordered.map((image, index) => ({ ...image, sort_order: index }));
    setImages(normalized); setDraggedImageId(null); setSavingImageOrder(true); setMessage("이미지 순서를 저장하고 있습니다.");
    const results = await Promise.all(normalized.map((image) => supabase.from("venue_images").update({ sort_order: image.sort_order }).eq("id", image.id)));
    const error = results.find((result) => result.error)?.error;
    if (error) { setImages(previous); setMessage(`이미지 순서 저장 실패: ${error.message}`); } else setMessage("이미지 순서를 저장했습니다.");
    setSavingImageOrder(false);
  };
  const makePrimaryImage = async (imageId: string) => {
    if (!supabase || images[0]?.id === imageId || savingImageOrder) return;
    const previous = images; const selectedImage = previous.find((image) => image.id === imageId); if (!selectedImage) return;
    const normalized = [selectedImage, ...previous.filter((image) => image.id !== imageId)].map((image, index) => ({ ...image, sort_order: index }));
    setImages(normalized); setSavingImageOrder(true); setMessage("대표 이미지를 저장하고 있습니다.");
    const results = await Promise.all(normalized.map((image) => supabase.from("venue_images").update({ sort_order: image.sort_order }).eq("id", image.id)));
    const error = results.find((result) => result.error)?.error;
    if (error) { setImages(previous); setMessage(`대표 이미지 저장 실패: ${error.message}`); } else setMessage("대표 이미지를 변경했습니다.");
    setSavingImageOrder(false);
  };

  return <AdminFrame><div className="admin-shell"><aside className="admin-sidebar"><div className="admin-sidebar-head"><div><span>MATRIX</span><strong>공연장 관리</strong></div><button onClick={addVenue}><Plus />추가</button></div><label className="admin-search"><Search /><input value={venueSearch} onChange={(event) => setVenueSearch(event.target.value)} placeholder="공연장 검색" /></label><div className="admin-venue-list">{visibleVenues.map((venue) => <button key={venue.id} onClick={() => setSelectedId(venue.id)} className={selectedId === venue.id ? "selected" : ""}><strong>{venue.name}</strong><span>{venue.area_label ?? "기타"}</span></button>)}</div><button className="admin-logout" onClick={() => void supabase?.auth.signOut()}><LogOut />로그아웃</button></aside><main className="admin-editor"><header><div><p>공연장 편집</p><h1>{form.name ?? "공연장 선택"}</h1></div><div><button className="danger" onClick={deleteVenue}><Trash2 />삭제</button><button className="save" onClick={save} disabled={saving}><Save />{saving ? "저장 중" : "저장"}</button></div></header>{message && <div className="admin-message">{message}</div>}<AdminSection title="기본 정보"><TextField label="공연장명" value={form.name} onChange={(value) => setForm({ ...form, name: value })} /><TextField label="주소 이름(Slug)" value={form.slug} onChange={(value) => setForm({ ...form, slug: value })} /><TextField label="공간 유형" value={form.venue_type} onChange={(value) => setForm({ ...form, venue_type: value })} /><TextField label="지역" value={form.area_label} onChange={(value) => setForm({ ...form, area_label: value })} /><TextField label="행정동" value={form.neighborhood} onChange={(value) => setForm({ ...form, neighborhood: value })} /><TextField label="주소" value={form.address_display} onChange={(value) => setForm({ ...form, address_display: value, location_verified: false })} /><TextField label="가까운 역" value={form.nearest_station} onChange={(value) => setForm({ ...form, nearest_station: value })} /><TextField label="수용 인원" type="number" value={form.capacity_people?.toString()} onChange={(value) => setForm({ ...form, capacity_people: value ? Number(value) : null })} /><TextField label="무대 크기" value={form.stage_size} onChange={(value) => setForm({ ...form, stage_size: value })} /><TextField label="연락처" value={form.phone} onChange={(value) => setForm({ ...form, phone: value })} /><TextField label="홈페이지 / SNS" value={form.official_url} onChange={(value) => setForm({ ...form, official_url: value })} /><TextField label="마지막 확인일" type="date" value={form.last_checked_at} onChange={(value) => setForm({ ...form, last_checked_at: value })} /><BoolField label="지도 위치 검증" value={String(form.location_verified ?? "")} onChange={(value) => setForm({ ...form, location_verified: nullableBool(value) === true })} /></AdminSection>
    <AdminSection title="대관료·출처"><TextField label="평일 가격 설명" value={details.weekday_text} onChange={(value) => setDetails({ ...details, weekday_text: value })} /><TextField label="평일 대표 가격(원)" type="number" value={details.weekday_price} onChange={(value) => setDetails({ ...details, weekday_price: value })} /><TextField label="주말 가격 설명" value={details.weekend_text} onChange={(value) => setDetails({ ...details, weekend_text: value })} /><TextField label="주말 대표 가격(원)" type="number" value={details.weekend_price} onChange={(value) => setDetails({ ...details, weekend_price: value })} /><TextField label="조사 출처 URL" type="url" value={details.source_url} onChange={(value) => setDetails({ ...details, source_url: value })} /></AdminSection>
    <AdminSection title="인력·음향 장비"><BoolField label="음향 엔지니어" value={details.sound_engineer} onChange={(value) => setDetails({ ...details, sound_engineer: value })} /><BoolField label="조명 엔지니어" value={details.lighting_operator} onChange={(value) => setDetails({ ...details, lighting_operator: value })} /><TextField label="오디오콘솔" value={details.foh_console} onChange={(value) => setDetails({ ...details, foh_console: value })} /><TextField label="메인 PA" value={details.main_pa} onChange={(value) => setDetails({ ...details, main_pa: value })} /><TextField label="모니터" value={details.monitor_system} onChange={(value) => setDetails({ ...details, monitor_system: value })} /><TextField label="유선 마이크" value={details.wired_mics} onChange={(value) => setDetails({ ...details, wired_mics: value })} /><TextField label="무선 마이크" value={details.wireless_mics} onChange={(value) => setDetails({ ...details, wireless_mics: value })} /><TextField label="DI 박스" value={details.di_boxes} onChange={(value) => setDetails({ ...details, di_boxes: value })} /></AdminSection>
    <AdminSection title="시설"><BoolField label="주차" value={details.parking} onChange={(value) => setDetails({ ...details, parking: value })} /><BoolField label="대기실" value={details.waiting_room} onChange={(value) => setDetails({ ...details, waiting_room: value })} /><BoolField label="엘리베이터" value={details.elevator} onChange={(value) => setDetails({ ...details, elevator: value })} /><BoolField label="장비 반입 편의" value={details.easy_load_in} onChange={(value) => setDetails({ ...details, easy_load_in: value })} /></AdminSection>
    <AdminSection title="장비"><div className="admin-equipment-list">{equipment.map((item, index) => <div key={`${item.category}-${index}`}><span>{equipmentCategoryLabels[item.category] ?? item.category}</span><p>{item.raw_description}</p><button onClick={async () => { await supabase!.from("venue_equipment").delete().eq("venue_id", selectedId).eq("category", item.category).eq("raw_description", item.raw_description); setEquipment(equipment.filter((_, itemIndex) => itemIndex !== index)); }}><X /></button></div>)}</div><div className="admin-equipment-add"><select value={newEquipment.category} onChange={(event) => setNewEquipment({ ...newEquipment, category: event.target.value })}><option value="drums">드럼</option><option value="guitar_amp">기타앰프</option><option value="bass_amp">베이스앰프</option><option value="keyboard">건반</option><option value="lighting_fixture">조명기</option><option value="lighting_console">조명 콘솔</option><option value="other">기타</option></select><input value={newEquipment.raw_description} onChange={(event) => setNewEquipment({ ...newEquipment, raw_description: event.target.value })} placeholder="장비 모델·수량" /><button onClick={async () => { if (!newEquipment.raw_description) return; const { error } = await supabase!.from("venue_equipment").insert({ venue_id: selectedId, ...newEquipment }); if (!error) { setEquipment([...equipment, newEquipment]); setNewEquipment({ ...newEquipment, raw_description: "" }); } }}><Plus />추가</button></div></AdminSection>
    <AdminSection title="대표 이미지"><label className={`image-upload ${uploadingImages ? "uploading" : ""}`}><Upload /><span>{uploadingImages ? `업로드 중 (${uploadProgress.current}/${uploadProgress.total})` : "여러 이미지 업로드"}</span><input type="file" accept="image/*" multiple disabled={uploadingImages} onChange={(event) => { const input = event.currentTarget; void uploadImages(input.files).finally(() => { input.value = ""; }); }} /></label><p className="admin-image-help">이미지를 드래그해 노출 순서를 변경하세요. 첫 번째 이미지가 대표 이미지로 표시됩니다.</p><div className="admin-images">{images.map((image, index) => <div key={image.id} className={`admin-image-card ${draggedImageId === image.id ? "dragging" : ""}`} draggable={!savingImageOrder && !uploadingImages} onDragStart={(event) => { event.dataTransfer.effectAllowed = "move"; setDraggedImageId(image.id); }} onDragOver={(event) => { event.preventDefault(); event.dataTransfer.dropEffect = "move"; }} onDrop={(event) => { event.preventDefault(); void moveImage(image.id); }} onDragEnd={() => setDraggedImageId(null)}><img src={image.public_url} alt={`${form.name ?? "공연장"} 이미지 ${index + 1}`} /><span className="admin-image-number">{index === 0 ? "대표" : index + 1}</span><span className="admin-image-drag"><GripVertical />드래그</span>{index > 0 && <button className="admin-image-primary" aria-label={`${index + 1}번 이미지를 대표 이미지로 지정`} onClick={() => void makePrimaryImage(image.id)}>대표 지정</button>}<button className="admin-image-delete" aria-label={`${index + 1}번 이미지 삭제`} onClick={async () => { await supabase!.storage.from("venue-images").remove([image.storage_path]); await supabase!.from("venue_images").delete().eq("id", image.id); setImages(images.filter((item) => item.id !== image.id)); }}><Trash2 /></button></div>)}{images.length === 0 && <div className="admin-no-image"><ImagePlus />등록된 이미지 없음</div>}</div></AdminSection></main></div></AdminFrame>;
}

function AdminFrame({ children }: { children: React.ReactNode }) { return <div className="admin-page"><div className="admin-top"><a href="/"><ArrowLeft />MATRIX로 돌아가기</a></div>{children}</div>; }
function AdminSection({ title, children }: { title: string; children: React.ReactNode }) { return <section className="admin-section"><h2>{title}</h2><div className="admin-form-grid">{children}</div></section>; }
function TextField({ label, value, onChange, type = "text" }: { label: string; value: string | null | undefined; onChange: (value: string) => void; type?: string }) { return <label className="admin-field"><span>{label}</span><input type={type} value={value ?? ""} onChange={(event) => onChange(event.target.value)} /></label>; }
function BoolField({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <label className="admin-field"><span>{label}</span><select value={value} onChange={(event) => onChange(event.target.value)}><option value="">확인 필요</option><option value="true">포함 / 가능</option><option value="false">미포함 / 불가</option></select></label>; }
