"use client";

/* eslint-disable @next/next/no-img-element */
import { useCallback, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { createClient, type SupabaseClient } from "@supabase/supabase-js";
import { ArrowLeft, ImagePlus, LogOut, Plus, Save, Trash2, Upload, X } from "lucide-react";

type Config = { url: string; anonKey: string };
type VenueRow = { id: string; slug: string; name: string; venue_type: string | null; district: string | null; neighborhood: string | null; area_label: string | null; address_display: string; nearest_station: string | null; phone: string | null; official_url: string | null; capacity_people: number | null; stage_size: string | null; last_checked_at: string | null; verification_status: string; location_verified: boolean; latitude: number | null; longitude: number | null };
type DetailState = { weekday_text: string; weekday_price: string; weekend_text: string; weekend_price: string; source_url: string; sound_engineer: string; lighting_operator: string; foh_console: string; main_pa: string; monitor_system: string; wired_mics: string; wireless_mics: string; di_boxes: string; parking: string; waiting_room: string; elevator: string; easy_load_in: string };
type EquipmentRow = { category: string; raw_description: string };
type ImageRow = { id: string; public_url: string; storage_path: string; sort_order: number };
const blankDetails: DetailState = { weekday_text: "", weekday_price: "", weekend_text: "", weekend_price: "", source_url: "", sound_engineer: "", lighting_operator: "", foh_console: "", main_pa: "", monitor_system: "", wired_mics: "", wireless_mics: "", di_boxes: "", parking: "", waiting_room: "", elevator: "", easy_load_in: "" };

function nullableBool(value: string) { return value === "true" ? true : value === "false" ? false : null; }

export function AdminConsole({ config }: { config: Config }) {
  const supabase = useMemo<SupabaseClient | null>(() => config.url && config.anonKey ? createClient(config.url, config.anonKey) : null, [config]);
  const [auth, setAuth] = useState<"loading" | "signed_out" | "checking" | "admin" | "denied">("loading");
  const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [message, setMessage] = useState("");
  const [venues, setVenues] = useState<VenueRow[]>([]); const [selectedId, setSelectedId] = useState<string>(""); const [form, setForm] = useState<Partial<VenueRow>>({});
  const [details, setDetails] = useState<DetailState>(blankDetails); const [equipment, setEquipment] = useState<EquipmentRow[]>([]); const [images, setImages] = useState<ImageRow[]>([]);
  const [newEquipment, setNewEquipment] = useState<EquipmentRow>({ category: "drums", raw_description: "" }); const [saving, setSaving] = useState(false);

  const loadVenues = useCallback(async () => { if (!supabase) return; const { data, error } = await supabase.from("venues").select("*").order("name"); if (error) setMessage(error.message); else { setVenues((data ?? []) as VenueRow[]); if (data?.[0]) setSelectedId((current) => current || data[0].id); } }, [supabase]);
  const checkAdmin = useCallback(async () => { if (!supabase) return; const { data: sessionData } = await supabase.auth.getSession(); const user = sessionData.session?.user; if (!user) { setAuth("signed_out"); return; } setAuth("checking"); const { data } = await supabase.from("admin_users").select("user_id").eq("user_id", user.id).maybeSingle(); setAuth(data ? "admin" : "denied"); if (data) await loadVenues(); }, [supabase, loadVenues]);

  useEffect(() => { if (!supabase) return; queueMicrotask(() => void checkAdmin()); const { data } = supabase.auth.onAuthStateChange(() => void checkAdmin()); return () => data.subscription.unsubscribe(); }, [supabase, checkAdmin]);

  useEffect(() => { const row = venues.find((venue) => venue.id === selectedId); if (!row || !supabase) return; void (async () => {
    setForm(row);
    const [staff, audio, facilities, rates, gear, photos, sources] = await Promise.all([
      supabase.from("venue_staff").select("*").eq("venue_id", row.id).maybeSingle(), supabase.from("audio_systems").select("*").eq("venue_id", row.id).maybeSingle(),
      supabase.from("venue_facilities").select("*").eq("venue_id", row.id).maybeSingle(), supabase.from("rental_rates").select("*").eq("venue_id", row.id),
      supabase.from("venue_equipment").select("category,raw_description").eq("venue_id", row.id), supabase.from("venue_images").select("*").eq("venue_id", row.id).order("sort_order"), supabase.from("sources").select("url,kind").eq("venue_id", row.id),
    ]);
    const weekday = rates.data?.find((rate) => rate.day_type === "weekday" || rate.day_type === "hourly"); const weekend = rates.data?.find((rate) => rate.day_type === "saturday" || rate.day_type === "sunday");
    setDetails({ weekday_text: weekday?.raw_text ?? "", weekday_price: weekday?.price_krw?.toString() ?? "", weekend_text: weekend?.raw_text ?? "", weekend_price: weekend?.price_krw?.toString() ?? "", source_url: sources.data?.find((source) => source.kind === "mule")?.url ?? "", sound_engineer: String(staff.data?.sound_engineer_included ?? ""), lighting_operator: String(staff.data?.lighting_operator_included ?? ""), foh_console: audio.data?.foh_console ?? "", main_pa: audio.data?.main_pa ?? "", monitor_system: audio.data?.monitor_system ?? "", wired_mics: audio.data?.wired_mics ?? "", wireless_mics: audio.data?.wireless_mics ?? "", di_boxes: audio.data?.di_boxes ?? "", parking: String(facilities.data?.parking ?? ""), waiting_room: String(facilities.data?.waiting_room ?? ""), elevator: String(facilities.data?.elevator ?? ""), easy_load_in: String(facilities.data?.easy_load_in ?? "") });
    setEquipment((gear.data ?? []) as EquipmentRow[]); setImages((photos.data ?? []) as ImageRow[]);
  })(); }, [selectedId, venues, supabase]);

  if (!config.url || !config.anonKey) return <AdminFrame><div className="admin-setup"><h1>Supabase 연결이 필요합니다</h1><p>관리자 로그인과 실시간 데이터 수정은 Supabase 환경 변수를 설정한 뒤 사용할 수 있습니다.</p><code>SUPABASE_URL<br/>SUPABASE_ANON_KEY</code><Link href="/">목록으로 돌아가기</Link></div></AdminFrame>;
  if (auth === "loading" || auth === "checking") return <AdminFrame><div className="admin-setup"><p>관리자 권한을 확인하고 있습니다.</p></div></AdminFrame>;
  if (auth === "signed_out") return <AdminFrame><form className="admin-login" onSubmit={async (event) => { event.preventDefault(); setMessage(""); const { error } = await supabase?.auth.signInWithPassword({ email, password }) ?? { error: new Error("연결 오류") }; if (error) setMessage(error.message); }}><p>MATRIX ADMIN</p><h1>관리자 로그인</h1><label>이메일<input type="email" value={email} onChange={(event) => setEmail(event.target.value)} required /></label><label>비밀번호<input type="password" value={password} onChange={(event) => setPassword(event.target.value)} required /></label>{message && <span>{message}</span>}<button type="submit">로그인</button><Link href="/">목록으로 돌아가기</Link></form></AdminFrame>;
  if (auth === "denied") return <AdminFrame><div className="admin-setup"><h1>접근 권한이 없습니다</h1><p>현재 계정은 MATRIX 관리자로 등록되지 않았습니다.</p><button onClick={() => void supabase?.auth.signOut()}>로그아웃</button></div></AdminFrame>;

  const save = async () => { if (!supabase || !selectedId) return; setSaving(true); setMessage(""); const base = { name: form.name, slug: form.slug, venue_type: form.venue_type || null, district: form.district || null, neighborhood: form.neighborhood || null, area_label: form.area_label || "기타", address_display: form.address_display, nearest_station: form.nearest_station || null, phone: form.phone || null, official_url: form.official_url || null, capacity_people: form.capacity_people ? Number(form.capacity_people) : null, stage_size: form.stage_size || null, last_checked_at: form.last_checked_at || null, verification_status: form.verification_status || "unverified", location_verified: Boolean(form.location_verified) };
    const results = await Promise.all([
      supabase.from("venues").update(base).eq("id", selectedId),
      supabase.from("venue_staff").upsert({ venue_id: selectedId, sound_engineer_included: nullableBool(details.sound_engineer), lighting_operator_included: nullableBool(details.lighting_operator) }),
      supabase.from("audio_systems").upsert({ venue_id: selectedId, foh_console: details.foh_console || null, main_pa: details.main_pa || null, monitor_system: details.monitor_system || null, wired_mics: details.wired_mics || null, wireless_mics: details.wireless_mics || null, di_boxes: details.di_boxes || null }),
      supabase.from("venue_facilities").upsert({ venue_id: selectedId, parking: nullableBool(details.parking), waiting_room: nullableBool(details.waiting_room), elevator: nullableBool(details.elevator), easy_load_in: nullableBool(details.easy_load_in) }),
    ]);
    const error = results.find((result) => result.error)?.error; if (!error) { await supabase.from("rental_rates").delete().eq("venue_id", selectedId).in("day_type", ["weekday", "saturday"]); const rates = [{ venue_id: selectedId, day_type: "weekday", raw_text: details.weekday_text, price_krw: details.weekday_price ? Number(details.weekday_price) : null }, { venue_id: selectedId, day_type: "saturday", raw_text: details.weekend_text, price_krw: details.weekend_price ? Number(details.weekend_price) : null }].filter((rate) => rate.raw_text); if (rates.length) await supabase.from("rental_rates").insert(rates); await supabase.from("sources").delete().eq("venue_id", selectedId).eq("kind", "mule"); if (details.source_url) await supabase.from("sources").insert({ venue_id: selectedId, kind: "mule", url: details.source_url }); setMessage("저장했습니다. 사용자 화면에 즉시 반영됩니다."); await loadVenues(); } else setMessage(error.message); setSaving(false); };
  const addVenue = async () => { if (!supabase) return; const suffix = Date.now().toString(36); const { data, error } = await supabase.from("venues").insert({ name: "새 공연장", slug: `new-venue-${suffix}`, address_display: "주소 입력 필요", area_label: "기타", verification_status: "unverified" }).select().single(); if (error) setMessage(error.message); else { await loadVenues(); setSelectedId(data.id); } };
  const deleteVenue = async () => { if (!supabase || !selectedId || !window.confirm("이 공연장과 연결된 정보를 삭제할까요?")) return; const { error } = await supabase.from("venues").delete().eq("id", selectedId); if (error) setMessage(error.message); else { setSelectedId(""); await loadVenues(); } };
  const uploadImages = async (files: FileList | null) => { if (!supabase || !selectedId || !files?.length) return; setMessage("이미지를 업로드하고 있습니다."); for (const file of Array.from(files)) { const safeName = `${selectedId}/${crypto.randomUUID()}-${file.name.replace(/[^a-zA-Z0-9._-]/g, "-")}`; const { error } = await supabase.storage.from("venue-images").upload(safeName, file, { upsert: false }); if (error) { setMessage(error.message); return; } const publicUrl = supabase.storage.from("venue-images").getPublicUrl(safeName).data.publicUrl; await supabase.from("venue_images").insert({ venue_id: selectedId, storage_path: safeName, public_url: publicUrl, sort_order: images.length }); } setMessage("이미지를 업로드했습니다."); setSelectedId((id) => `${id}`); window.location.reload(); };

  return <AdminFrame><div className="admin-shell"><aside className="admin-sidebar"><div className="admin-sidebar-head"><div><span>MATRIX</span><strong>공연장 관리</strong></div><button onClick={addVenue}><Plus />추가</button></div><div className="admin-venue-list">{venues.map((venue) => <button key={venue.id} onClick={() => setSelectedId(venue.id)} className={selectedId === venue.id ? "selected" : ""}><strong>{venue.name}</strong><span>{venue.area_label ?? "기타"}</span></button>)}</div><button className="admin-logout" onClick={() => void supabase?.auth.signOut()}><LogOut />로그아웃</button></aside><main className="admin-editor"><header><div><p>VENUE EDITOR</p><h1>{form.name ?? "공연장 선택"}</h1></div><div><button className="danger" onClick={deleteVenue}><Trash2 />삭제</button><button className="save" onClick={save} disabled={saving}><Save />{saving ? "저장 중" : "저장"}</button></div></header>{message && <div className="admin-message">{message}</div>}<AdminSection title="기본 정보"><TextField label="공연장명" value={form.name} onChange={(value) => setForm({ ...form, name: value })} /><TextField label="Slug" value={form.slug} onChange={(value) => setForm({ ...form, slug: value })} /><TextField label="공간 유형" value={form.venue_type} onChange={(value) => setForm({ ...form, venue_type: value })} /><TextField label="지역" value={form.area_label} onChange={(value) => setForm({ ...form, area_label: value })} /><TextField label="행정동" value={form.neighborhood} onChange={(value) => setForm({ ...form, neighborhood: value })} /><TextField label="주소" value={form.address_display} onChange={(value) => setForm({ ...form, address_display: value, location_verified: false })} /><TextField label="가까운 역" value={form.nearest_station} onChange={(value) => setForm({ ...form, nearest_station: value })} /><TextField label="수용 인원" type="number" value={form.capacity_people?.toString()} onChange={(value) => setForm({ ...form, capacity_people: value ? Number(value) : null })} /><TextField label="무대 크기" value={form.stage_size} onChange={(value) => setForm({ ...form, stage_size: value })} /><TextField label="연락처" value={form.phone} onChange={(value) => setForm({ ...form, phone: value })} /><TextField label="홈페이지 / SNS" value={form.official_url} onChange={(value) => setForm({ ...form, official_url: value })} /><TextField label="마지막 확인일" type="date" value={form.last_checked_at} onChange={(value) => setForm({ ...form, last_checked_at: value })} /></AdminSection>
    <AdminSection title="대관료·출처"><TextField label="평일 가격 설명" value={details.weekday_text} onChange={(value) => setDetails({ ...details, weekday_text: value })} /><TextField label="평일 대표 가격(원)" type="number" value={details.weekday_price} onChange={(value) => setDetails({ ...details, weekday_price: value })} /><TextField label="주말 가격 설명" value={details.weekend_text} onChange={(value) => setDetails({ ...details, weekend_text: value })} /><TextField label="주말 대표 가격(원)" type="number" value={details.weekend_price} onChange={(value) => setDetails({ ...details, weekend_price: value })} /><TextField label="조사 출처 URL" type="url" value={details.source_url} onChange={(value) => setDetails({ ...details, source_url: value })} /></AdminSection>
    <AdminSection title="인력·Technical"><BoolField label="음향 엔지니어" value={details.sound_engineer} onChange={(value) => setDetails({ ...details, sound_engineer: value })} /><BoolField label="조명 오퍼레이터" value={details.lighting_operator} onChange={(value) => setDetails({ ...details, lighting_operator: value })} /><TextField label="FOH Console" value={details.foh_console} onChange={(value) => setDetails({ ...details, foh_console: value })} /><TextField label="Main PA" value={details.main_pa} onChange={(value) => setDetails({ ...details, main_pa: value })} /><TextField label="Monitor" value={details.monitor_system} onChange={(value) => setDetails({ ...details, monitor_system: value })} /><TextField label="유선 마이크" value={details.wired_mics} onChange={(value) => setDetails({ ...details, wired_mics: value })} /><TextField label="무선 마이크" value={details.wireless_mics} onChange={(value) => setDetails({ ...details, wireless_mics: value })} /><TextField label="DI" value={details.di_boxes} onChange={(value) => setDetails({ ...details, di_boxes: value })} /></AdminSection>
    <AdminSection title="시설"><BoolField label="주차" value={details.parking} onChange={(value) => setDetails({ ...details, parking: value })} /><BoolField label="대기실" value={details.waiting_room} onChange={(value) => setDetails({ ...details, waiting_room: value })} /><BoolField label="엘리베이터" value={details.elevator} onChange={(value) => setDetails({ ...details, elevator: value })} /><BoolField label="장비 반입 편의" value={details.easy_load_in} onChange={(value) => setDetails({ ...details, easy_load_in: value })} /></AdminSection>
    <AdminSection title="장비"><div className="admin-equipment-list">{equipment.map((item, index) => <div key={`${item.category}-${index}`}><span>{item.category}</span><p>{item.raw_description}</p><button onClick={async () => { await supabase!.from("venue_equipment").delete().eq("venue_id", selectedId).eq("category", item.category).eq("raw_description", item.raw_description); setEquipment(equipment.filter((_, itemIndex) => itemIndex !== index)); }}><X /></button></div>)}</div><div className="admin-equipment-add"><select value={newEquipment.category} onChange={(event) => setNewEquipment({ ...newEquipment, category: event.target.value })}><option value="drums">Drum</option><option value="guitar_amp">Guitar Amp</option><option value="bass_amp">Bass Amp</option><option value="keyboard">Keyboard</option><option value="lighting_fixture">Lighting</option><option value="lighting_console">Lighting Console</option><option value="other">기타</option></select><input value={newEquipment.raw_description} onChange={(event) => setNewEquipment({ ...newEquipment, raw_description: event.target.value })} placeholder="장비 모델·수량" /><button onClick={async () => { if (!newEquipment.raw_description) return; const { error } = await supabase!.from("venue_equipment").insert({ venue_id: selectedId, ...newEquipment }); if (!error) { setEquipment([...equipment, newEquipment]); setNewEquipment({ ...newEquipment, raw_description: "" }); } }}><Plus />추가</button></div></AdminSection>
    <AdminSection title="대표 이미지"><label className="image-upload"><Upload /><span>여러 이미지 업로드</span><input type="file" accept="image/*" multiple onChange={(event) => void uploadImages(event.target.files)} /></label><div className="admin-images">{images.map((image) => <div key={image.id}><img src={image.public_url} alt="" /><button onClick={async () => { await supabase!.storage.from("venue-images").remove([image.storage_path]); await supabase!.from("venue_images").delete().eq("id", image.id); setImages(images.filter((item) => item.id !== image.id)); }}><Trash2 /></button></div>)}{images.length === 0 && <div className="admin-no-image"><ImagePlus />등록된 이미지 없음</div>}</div></AdminSection></main></div></AdminFrame>;
}

function AdminFrame({ children }: { children: React.ReactNode }) { return <div className="admin-page"><div className="admin-top"><Link href="/"><ArrowLeft />MATRIX로 돌아가기</Link></div>{children}</div>; }
function AdminSection({ title, children }: { title: string; children: React.ReactNode }) { return <section className="admin-section"><h2>{title}</h2><div className="admin-form-grid">{children}</div></section>; }
function TextField({ label, value, onChange, type = "text" }: { label: string; value: string | null | undefined; onChange: (value: string) => void; type?: string }) { return <label className="admin-field"><span>{label}</span><input type={type} value={value ?? ""} onChange={(event) => onChange(event.target.value)} /></label>; }
function BoolField({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <label className="admin-field"><span>{label}</span><select value={value} onChange={(event) => onChange(event.target.value)}><option value="">확인 필요</option><option value="true">포함 / 가능</option><option value="false">미포함 / 불가</option></select></label>; }
